extends SceneTree

const Simulation := preload("res://simulation.gd")


func _initialize() -> void:
	var archive := preload("res://history_archive.gd").new()
	var total_records := 0
	for archive_year in range(1980, 1985):
		for archive_month in range(1, 13):
			var records := archive.load_month(archive_year, archive_month)
			assert(records.size() == 18)
			for topic in archive.TOPICS:
				assert(records.filter(func(record: Dictionary) -> bool: return record.topic_class == topic).size() == 3)
			for record in records:
				assert(not archive.source_text(record).is_empty())
			total_records += records.size()
	assert(total_records == 1080)
	assert(archive.load_month(1985, 1).is_empty() and not archive.status.is_empty())
	print("PASS: all 60 archive months, 1080 records, topic counts, sources, and missing coverage.")
	var model := Simulation.new()
	assert(model.queue_order(0, true, 8).is_empty())
	assert(model.holdings[0] == 0 and model.cash == 100.0)
	assert(model.available_cash() == 20.0 and model.net_worth() == 100.0)
	assert(not model.queue_order(0, true, 3).is_empty())
	assert(not model.queue_order(0, false, 1).is_empty())
	model.cancel_order(1)
	assert(model.available_cash() == 100.0)
	assert(model.queue_order(0, true, 8).is_empty())
	assert(model.advance().size() == 1)
	assert(model.holdings[0] == 8 and model.cash == 20.0)
	assert(model.federal_heat > 0.0 and model.criminal_heat == 0.0)
	assert(model.queue_order(0, false, 8).is_empty())
	assert(not model.queue_order(0, false, 1).is_empty())
	assert(model.holdings[0] == 8)
	model.advance()
	assert(model.holdings[0] == 0 and model.orders.is_empty())
	var property := Simulation.new()
	property.cash = 500000.0
	assert(property.delay(3) == 3 and property.delay(4) == 4)
	assert(property.queue_order(3, true, 1).is_empty())
	assert(property.queue_order(4, true, 1).is_empty())
	property.advance()
	property.advance()
	assert(property.holdings[3] == 0 and property.holdings[4] == 0)
	property.advance()
	assert(property.holdings[3] == 1 and property.holdings[4] == 0)
	assert(property.delay(3) == 1 and property.delay(4) == 2)
	property.advance()
	assert(property.holdings[4] == 1 and property.cash == 305000.0)
	assert(property.federal_heat > 0.0 and property.criminal_heat == 0.0)
	assert(property.queue_order(3, false, 1).is_empty())
	property.advance()
	assert(property.holdings[3] == 0)
	property.elapsed = 11
	assert(property.delay(3) == 3)
	assert(property.queue_order(3, true, 1).is_empty())
	assert(property.orders[0].due == 14)
	property.cancel_order(property.orders[0].id)
	assert(property.reserved_cash() == 0.0)
	var heat_model := Simulation.new()
	heat_model.federal_heat = 5.0
	assert(heat_model.queue_order(0, true, 1).is_empty())
	heat_model.cancel_order(1)
	assert(heat_model.federal_heat == 5.0 and heat_model.criminal_heat == 0.0)
	heat_model.advance()
	assert(heat_model.federal_heat == 4.0 and heat_model.criminal_heat == 0.0)
	print("PASS: stock/property settlements affect federal heat only; cancellations add no heat; federal heat decays independently.")
	print("PASS: reservations, insufficient funds, overselling, cancellation, stock settlement, seasonal property settlement, year rollover.")
	call_deferred("_verify_dashboard")


func _verify_dashboard() -> void:
	var dashboard = load("res://dashboard.tscn").instantiate()
	root.add_child(dashboard)
	await process_frame
	assert(dashboard.history_records.size() == 18)
	dashboard.news_filter.select(4)
	dashboard._render_news()
	assert(dashboard.news_feed.get_child_count() == 3)
	dashboard.news_filter.select(0)
	dashboard._render_news()
	dashboard.stock_window.popup_centered()
	dashboard.stock_window.submit_order()
	assert(dashboard.simulation.orders.size() == 1)
	dashboard.stock_window.hide()
	assert(dashboard.stock_window.asset_picker.item_count == 3)
	assert(dashboard.property_window.asset_picker.item_count == 2)
	assert(dashboard.property_window.asset_picker.get_selected_id() == 3)
	dashboard.simulation.cash = 200000.0
	dashboard.property_window.submit_order()
	assert(dashboard.simulation.orders.size() == 2)
	assert(dashboard.stock_window.pending.get_child_count() == 1)
	assert(dashboard.property_window.pending.get_child_count() == 1)
	assert(dashboard.simulation.orders[1].asset == 3)
	dashboard.property_window.cancel_order(dashboard.simulation.orders[1].id)
	assert(dashboard.simulation.orders.size() == 1)
	dashboard._advance_month()
	assert(dashboard.simulation.holdings[0] == 1)
	assert(dashboard.date_label.text == "February 1980")
	assert(dashboard.history_records.size() == 18)
	assert(str(dashboard.history_records[0].date).begins_with("1980-02"))
	dashboard.visibility_window.popup_centered()
	await process_frame
	dashboard.visibility_window.hide()
	print("PASS: portfolio submission, embedded windows, calendar and dashboard settlement refresh.")
	quit()
